# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

scal:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
        KERNEL_ID: kernel_id
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    kernel_id:
      - 0
      - 1
    warps:
      - 4
      - 8
    stages:
      - 2
      - 3
relu:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 4
      - 8
    stages:
      - 2
      - 3
gelu:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 4
      - 8
    stages:
      - 2
      - 3
silu:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 4
      - 8
    stages:
      - 2
      - 3
leaky_relu:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 4
      - 8
    stages:
      - 2
      - 3
prelu:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 1
      - 2
      - 3
softmax:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096      # 针对大词表新增的大块读取
      - 8192      # 极限显存吞吐块大小
    warps:
      - 4
      - 8
      - 16
      - 32
    stages:
      - 2
      - 3
      - 4         # 增加流水线深度，有助于掩盖大块访存延迟
batch_norm:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      # - 512
      # - 1024
      # - 2048
      # - 4096
      # - 8192
    warps:
      # - 4
      - 8
    #   - 16
    #   - 32
    stages:
      - 2
    #   - 3
    #   - 4
pow:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
sqrt:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 4
      - 8
    stages:
      - 2
      - 3
abs:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 4
      - 8
    stages:
      - 2
      - 3
neg:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 4
      - 8
    stages:
      - 2
      - 3
clamp:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 4
      - 8
    stages:
      - 2
      - 3
binary:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
layer_norm:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
rms_norm:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
group_norm:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
max_pool1d:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
avg_pool1d:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
max_pool2d:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
avg_pool2d:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
max_pool3d:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
avg_pool3d:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
adaptive_max_pool1d:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
adaptive_max_pool2d:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
adaptive_max_pool3d:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
adaptive_avg_pool1d_global:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
adaptive_avg_pool1d_divisible_large:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 16
      - 32
      - 64
      - 128
    warps:
      - 1
      - 2
      - 4
    stages:
      - 1
      - 2
adaptive_avg_pool1d_general_large:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 16
      - 32
      - 64
      - 128
    warps:
      - 1
      - 2
      - 4
    stages:
      - 1
      - 2
adaptive_avg_pool2d_global:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 32
      - 64
      - 128
      - 256
      - 512
    warps:
      - 1
      - 2
      - 4
    stages:
      - 1
      - 2
      - 3
adaptive_avg_pool2d_divisible_large:
  - gen: true
    param_map:
      META:
        BLOCK_H: block_h
        BLOCK_W: block_w
      num_warps: warps
      num_stages: stages
    block_h:
      - 1
      - 2
      - 4
      - 8
    block_w:
      - 4
      - 8
      - 16
    warps:
      - 1
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
      - 3
adaptive_avg_pool2d_general_large:
  - gen: true
    param_map:
      META:
        BLOCK_H: block_h
        BLOCK_W: block_w
      num_warps: warps
      num_stages: stages
    block_h:
      - 1
      - 2
      - 4
      - 8
    block_w:
      - 4
      - 8
      - 16
    warps:
      - 1
      - 2
      - 4
    stages:
      - 1
      - 2
adaptive_avg_pool3d_global:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 32
      - 64
      - 128
      - 256
      - 512
      - 1024
      - 2048
    warps:
      - 2
      - 4
      - 8
      - 16
    stages:
      - 1
      - 2
      - 3
      - 4
adaptive_avg_pool3d_divisible_large:
  - gen: true
    param_map:
      META:
        BLOCK_D: block_d
        BLOCK_H: block_h
        BLOCK_W: block_w
      num_warps: warps
      num_stages: stages
    block_d:
      - 1
      - 2
      - 4
    block_h:
      - 1
      - 2
      - 4
      - 8
    block_w:
      - 4
      - 8
      - 16
    warps:
      - 1
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
      - 3
adaptive_avg_pool3d_general_large:
  - gen: true
    param_map:
      META:
        BLOCK_D: block_d
        BLOCK_H: block_h
        BLOCK_W: block_w
      num_warps: warps
      num_stages: stages
    block_d:
      - 1
      - 2
      - 4
    block_h:
      - 1
      - 2
      - 4
      - 8
    block_w:
      - 4
      - 8
      - 16
    warps:
      - 1
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
      - 3
threshold:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
hardtanh:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
elu:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
rrelu:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
mish:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
      - 2048
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
softsign:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
softplus:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
softshrink:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
softmin:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
      - 8192
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
softmin_fp64:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 2
      - 4
      - 8
    stages:
      - 2
      - 3
mv:
  - gen: true
    param_map:
      META:
        BLOCK_M: block_m
        BLOCK_N: block_n
      num_warps: warps
      num_stages: stages
    block_m:
      - 1
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
    block_n:
      - 32
      - 64
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
mv_wide:
  - gen: true
    param_map:
      META:
        BLOCK_N: block_n
      num_warps: warps
      num_stages: stages
    block_n:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
mv_fp64:
  - gen: true
    param_map:
      META:
        BLOCK_M: block_m
        BLOCK_N: block_n
      num_warps: warps
      num_stages: stages
    block_m:
      - 1
      - 2
      - 4
      - 8
      - 16
      - 32
    block_n:
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
      - 5
mv_wide_fp64:
  - gen: true
    param_map:
      META:
        BLOCK_N: block_n
      num_warps: warps
      num_stages: stages
    block_n:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
    warps:
      - 2
      - 4
      - 8
      - 16
    stages:
      - 2
      - 3
      - 4
      - 5
skinny_mm:
  - META:
      BLOCK_M: 16
      BLOCK_N: 64
      BLOCK_K: 32
      GROUP_M: 8
    num_warps: 4
    num_stages: 3
  - META:
      BLOCK_M: 32
      BLOCK_N: 64
      BLOCK_K: 32
      GROUP_M: 8
    num_warps: 4
    num_stages: 3
  - META:
      BLOCK_M: 16
      BLOCK_N: 128
      BLOCK_K: 32
      GROUP_M: 8
    num_warps: 4
    num_stages: 3
  - META:
      BLOCK_M: 32
      BLOCK_N: 128
      BLOCK_K: 32
      GROUP_M: 8
    num_warps: 4
    num_stages: 3
  - META:
      BLOCK_M: 64
      BLOCK_N: 64
      BLOCK_K: 32
      GROUP_M: 8
    num_warps: 4
    num_stages: 3
  - META:
      BLOCK_M: 64
      BLOCK_N: 128
      BLOCK_K: 32
      GROUP_M: 8
    num_warps: 4
    num_stages: 3
  - META:
      BLOCK_M: 32
      BLOCK_N: 256
      BLOCK_K: 32
      GROUP_M: 4
    num_warps: 4
    num_stages: 3
  - META:
      BLOCK_M: 64
      BLOCK_N: 256
      BLOCK_K: 32
      GROUP_M: 4
    num_warps: 8
    num_stages: 3
dot:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
        UNROLL: unroll
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    unroll:
      - 2
      - 4
      - 8
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2

dot_fp64:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
        UNROLL: unroll
      num_warps: warps
      num_stages: stages
    block_size:
      - 64
      - 128
      - 256
      - 512
    unroll:
      - 2
      - 4
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
hardswish:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
relu6:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
selu:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
celu:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
glu:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
tanh:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
logsigmoid:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
      - 256
      - 512
      - 1024
    warps:
      - 2
      - 4
      - 8
    stages:
      - 1
      - 2
conv1d_gemm_v3:
  - gen: true
    param_map:
      META:
        BLOCK_M: block_m
        BLOCK_OC: block_oc
        BLOCK_K: block_k
      num_warps: warps
      num_stages: stages
    block_m:
      - 32
      - 64
      - 128
    block_oc:
      - 32
      - 64
      - 128
    block_k:
      - 32
      - 64
    warps:
      - 4
    stages:
      - 2
conv1d_general:
  - gen: true
    param_map:
      META:
        BLOCK_SIZE: block_size
      num_warps: warps
      num_stages: stages
    block_size:
      - 128
    warps:
      - 4
    stages:
      - 1
conv1d_depthwise_v5:
  - gen: true
    param_map:
      META:
        BLOCK_C: block_c
        BLOCK_L: block_l
      num_warps: warps
      num_stages: stages
    block_c:
      - 8
      - 16
      - 32
    block_l:
      - 128
      - 256
    warps:
      - 4
    stages:
      - 2
